# Node ID: [X Location, Y Location, Controllable?]

Nodes:
  1: [0, 0, true]
  2: [10, 0, true]
  3: [20, 0, true]
  # 4: [30, 0, true]
  # 5: [40, 0, true]
  # 6: [50, 0, true]
  # 7: [60, 0, true]
  # 8: [70, 0, true]
  # 9: [80, 0, true]
  # 10: [90, 0, true]
  # 11: [100, 0, true]
  # 12: [110, 0, true]
  # 13: [120, 0, true]
  # 14: [130, 0, true]
  # 15: [140, 0, true]
  # 16: [150, 0, true]
  # 17: [160, 0, true]
  # 18: [170, 0, true]
  # 19: [180, 0, true]
  # 20: [190, 0, true]
  # 21: [200, 0, true]
  # 22: [210, 0, true]
  # 23: [220, 0, true]
  # 24: [230, 0, true]
  # 25: [240, 0, true]
  # 26: [250, 0, true]
  # 27: [260, 0, true]
  # 28: [270, 0, true]
  # 29: [280, 0, true]
  # 30: [290, 0, true]

Sink : [90, 0]